feat: return content headers on head request
LeTrovoes/http-server pull request #2
Opened 2020-06-07 19:55 UTC by LeTrovoes

Goal:
- Send Content-Length and Content-Type headers on HEAD request

Yet to be done:
- Send correct encoding (charset) in Content-Type header

2020-06-08 03:23 UTC, LJC-DB requested changes
Criar Head como filha de Response

2020-06-08 03:26 UTC, LJC-DB reviewed
Ao invés de criar a mensagem completa tendo que ler o arquivo inteiro, podemos criar uma mensagem header e apenas adicionar o body nela.
Acredito que apenas OK utilize o body, logo mover os métodos referentes a isso para ela.
Visto que OK e HEAD são iguais com exceção do body, podemos fazer OK sendo filha de HEAD.

2020-06-09 04:04 UTC, LeTrovoes commented
> Acredito que apenas OK utilize o body, logo mover os métodos referentes a isso para ela.
Não necessariamente. As outras respostar também podem ter body, coisa que eu queria fazer também pro 404 não ser uma tela branca no browser.

2020-06-09 04:14 UTC, LeTrovoes commented
> Ao invés de criar a mensagem completa tendo que ler o arquivo inteiro

Se conseguirmos pegar o tamanho do arquivo sem ler, pode ser.

2020-06-09 04:18 UTC, LeTrovoes commented
Será refeita de forma a não precisar ler o arquivo no HEAD

2020-06-09 04:18 UTC, closed without merging